### PR TITLE
feat(os_linux): add `poll` & `ppoll`

### PR DESCRIPTION
**Pull request by GoNZooo**
I wanted to play around with `poll` & friends in a project and noticed that we didn't have them in `os_linux` (while we obviously still have Windows equivalents).

It's not necessarily what people will go with in practice (they'll probably want `io_uring`), but I think it's still nice to have access to.

### CODE REVIEW

**Comment by jasonKercher** [comment]
Linux does not have a `poll` syscall for arm64.  Maybe you can wrap `ppoll` for arm64 there.  

Also, I'm not sure about your definition of `sigset_t`.  Where did you get that.  I *believe* it should only ever be 4 or 8 (if you include the real-time signals).

**Comment by GoNZooo** [comment]
@jasonKercher The builds are passing and the formatting should be cleaned up.

**Comment by GoNZooo** [comment]
The Windows pipeline seems to fail on a completely unrelated test(?)

**Comment by Kelimion** [comment]
> The Windows pipeline seems to fail on a completely unrelated test(?)

It does that sometimes for no clear reason.

**Pull request merged**
