### PR TITLE
`core:flags`

### PR DESCRIPTION
**Pull request by gingerBill**
Based on the Feoramund's original package: https://github.com/Feoramund/odin-varg

### CODE REVIEW

**Comment by Feoramund** [comment]
I was going to put up a PR for this within the week, but I wanted to get the rewrite really solid.

I'm almost done with it on my local branch. It may take another day or two though, since I was busy with the test runner, but now I have a bit more time. I got UNIX flags working, enum parsing, complete documentation, lots of little goodies I think everyone will enjoy.

If you want to go ahead with this, that'll be fine. I can make a second PR later that'll augment this feature set if you merge it before I get to it. Just let me know how you want to proceed.

You did solve one problem for me though. I wasn't sure where I was going to put the package. Thought of `core:strings/` or `core:os/`, but this is cool too. :)

**Comment by gingerBill** [comment]
I think `core:flags` is a good place to put it.

This is a draft PR for a reason, and might not be merged, especially if you have a really solid rewrite! @

**Comment by Feoramund** [comment]
I should be able to get the PR up within a day now. I have to do one last review of the rewrite, but functionally, it's sound.

**Comment by Kelimion** [comment]
Closed in favor of #3700

**Pull request closed without merging**
