### PR TITLE
update to build for freebsd

### PR DESCRIPTION
**Pull request by hoanga**
hello,

the following patches fix the compilation on freebsd.

the following packages are suggested for installation (for some reason needed llvm11 specifically even though (more recent) freebsd should include llvm as its default compiler)

```
pkg install llvm11 gmake
```

the following sample run was tested on a freebsd 13 jail.

```sh
# uname -s
FreeBSD

# gmake
clang src/main.cpp src/libtommath.cpp -Wno-switch -Wno-macro-redefined -Wno-unused-value -std=c++14 -DGIT_SHA=\"9848e883\" -DODIN_VERSION_RAW=\"dev-2022-03\" -I/usr/local/llvm11/include -std=c++14   -fno-exceptions -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -L/usr/local/llvm11/lib  -g -pthread -lm -lstdc++ -lLLVM-11 -o odin
./odin run examples/demo/demo.odin

# the basics
Hellope

# control flow
0
1
2
3
4
5
6
7
8
9
0
1
2
3
4
5
6
7
8
9
0
1
2
3
4
5
6
7
8
9
0
1
2
3
4
5
6
7
8
9
H
e
l
l
o
,

世
界
1
4
9
1
4
9
1
4
9
A
C
B
0 H
1 e
2 l
3 l
4 o
5 ,
6
7 世
10 界
0 1
1 4
2 9
0 1
1 4
2 9
0 1
1 4
2 9
A 1
C 9
B 4
x is positive
y is negative
y is positive
64-bit
x is positive
c is alphanumeric
4
234
1
2
3
2
1
64 bit
one_step
beyond

# named proc return parameters
foo0 = 123
foo1 = 123
foo2 = 567 321

# explicit procedure overloading
add_ints 3
add_floats 3.000
add_numbers 6
add_ints 3
add_floats 3.000
add_numbers 6

# struct type
4.000
Vector2{x = 1335.000, y = 2.000}

# union type
137
true
nil
137
true
nil
I'm a monster

# using statement
0.000 0.000 0.000
0.000 0.000 0.000

# implicit context system

# parametric polymorphism
print_value: int 1
print_value: f32 2.100
print_value: f64 3.140
print_value: string message

a: int = 7
b: f64 = 7.500
13
`found` is 36
`found` is 42
Para_Union(int)
nil
123
Foo0
Generating an array of type [4]int from the value 4 of type int

# array programming
[0.5, 3.0, 6.5]
22.0
[-4.000, 8.000, -4.000]
0.000

# map type
2

# implicit selector expression
HITHER
468

# partial_switch
A
A
int

# cstring_example
Hellope Hellope Hellope
7 7 7
7 7 7

# bit_set type
Days{Sunday, Monday} Days{Sunday, Monday, Saturday}
true
Saturday in Days{Sunday, Monday, Saturday}
true
Cardinality: 3
bit_set['A'..'Z']
bit_set[0..8; u16]

# deferred procedure associations
Welcome
Something in the middle, mate.
Goodbye? true

# reflection
Foo :: struct {
        x: int `tag1`,
        y: string `json:"y_field"`,
        z: bool,
}
json: y -> y_field

# quaternions
(1.000+2.000i+3.000j+4.000k) * (5.000+6.000i+7.000j+8.000k) = -60.000+12.000i+30.000j+24.000k
(1.000+2.000i+3.000j+4.000k) / (5.000+6.000i+7.000j+8.000k) = 0.402-0.276i+0.000j+0.253k
(1.000+2.000i+3.000j+4.000k) + (5.000+6.000i+7.000j+8.000k) = 6.000+8.000i+10.000j+12.000k
(1.000+2.000i+3.000j+4.000k) - (5.000+6.000i+7.000j+8.000k) = -4.000-4.000i-4.000j-4.000k
q = 1.000+2.000i+3.000j+4.000k
real(q) = 1.000
imag(q) = 2.000
jmag(q) = 3.000
kmag(q) = 4.000
conj(q) = 1.000-2.000i-3.000j-4.000k
abs(q)  = 5.477
1.000+2.000i
1.000+2.000i+0.000j+0.000k
Quaternion memory layout: xyzw/(ijkr)
1.000+2.000i+3.000j+4.000k
[2.000, 3.000, 4.000, 1.000]

#'#unroll for' statements
Ranges
1 0
2 1
3 2
Strings
H 0
e 1
l 2
l 3
o 4
, 5
  6
世 7
界 10
Arrays
1 0
4 1
9 2
16 3
Enum types
A 0
B 1
C 2
D 3

#procedure 'where' clauses
-13
[12.000, -48.000, -12.000]
foo was called with the parameter [1, 2, 3]
bar was called with the parameter [4, 9]

#foreign system

#ranged fields for array compound literals
[1, 4, 9, 16]
[1, 4, 9, 16]
[123, 0, 0, 0, 0, 54, 54, 54, 54, 54, 8, 8, 8, 8, 8, 8]
[123, 0, 0, 0, 0, 54, 54, 54, 54, 54, 8, 8, 8, 8, 8, 8]
[123, 0, 0, 0, 0, 54, 54, 54, 54, 54, 8, 8, 8, 8, 8, 8]

#range statements with multiple return values
0
1
4
9
16
25
0 0
1 1
4 2
9 3
16 4
25 5
0
1
4
9
16
25

# threading_example

## Basic Threads
Thread 0 is on iteration 1
`White`: iteration 1
Thread Thread 21 is on iteration  is on iteration 1Thread Thread 14
 is on iteration 31`Red is on iteration

1`Thread
``BlueOctarine`: iteration Green`: iteration `: iteration 111


`: iteration 1
5 is on iteration 1
`Black`: iteration 1
Thread 0 is on iteration 2
`White`: iteration 2
Thread 4 is on iteration 2Thread
`Thread OctarineThread 325 is on iteration  is on iteration 22
 is on iteration `2

Thread `1Blue`: iteration `Black2Green
`: iteration `: iteration 22

 is on iteration 2`: iteration
2`
Red`: iteration 2
Thread 0 is on iteration 3
`White`: iteration 3
Thread 4 is on iteration 3
`Octarine`: iteration 3
Thread Thread 52 is on iteration  is on iteration 33

`Thread Thread `31 is on iteration BlackGreen3`: iteration
``: iteration 3 is on iteration 33
Red
`: iteration
`3Blue`: iteration
3
Thread 0 is on iteration 4
`White`: iteration 4
Thread 4 is on iteration 4
`Octarine`: iteration 4
Thread Thread 1 is on iteration 54Thread Thread
`3Red is on iteration `: iteration 4
42
 is on iteration `4
`BlueGreen`: iteration `: iteration 44
 is on iteration
4
`Black`: iteration 4
Thread 0 is on iteration 5
`White`: iteration 5
Thread 4 is on iteration 5
`Octarine`: iteration 5
Thread 1 is on iteration 5
`Red`: iteration 5
Thread Thread Thread 23 is on iteration  is on iteration 55

``GreenBlue`: iteration `: iteration 55

Thread 0 is done
Thread 4 is done
Thread 1 is done
Thread 2 is done
Thread 3 is done
5 is on iteration 5
`Black`: iteration 5
Thread 5 is done

## Thread Pool
Worker Task 0 is on iteration 1
`Worker Task White`: iteration Worker Task Worker Task 12
31 is on iteration 1
 is on iteration  is on iteration `1Red
`: iteration `1Blue
`: iteration 1
1
`Green`: iteration 1
Worker Task 0 is on iteration 2
`White`: iteration 2
Worker Task 3 is on iteration 2
`Blue`: iteration 2
Worker Task 1 is on iteration 2
`Red`: iteration 2
Worker Task 2 is on iteration 2
`Green`: iteration 2
Worker Task 0 is on iteration 3
`White`: iteration 3
Worker Task 3 is on iteration 3
`Blue`: iteration 3
Worker Task 1 is on iteration 3
`Red`: iteration 3
Worker Task 2 is on iteration 3
`Green`: iteration 3
Worker Task 0 is on iteration 4
`White`: iteration 4
Worker Task 3 is on iteration 4
`Blue`: iteration 4
Worker Task 1 is on iteration 4
`Red`: iteration 4
Worker Task 2 is on iteration 4
`Green`: iteration 4
Worker Task 0 is on iteration 5
`White`: iteration 5
Worker Task 3 is on iteration 5
`Blue`: iteration 5
Worker Task 1 is on iteration 5
`Red`: iteration 5
Worker Task 2 is on iteration 5
`Green`: iteration 5
Worker Task 4 is on iteration 1
`Octarine`: iteration 1
Worker Task 5 is on iteration 1
`Black`: iteration 1
Worker Task 6 is on iteration 1
`White`: iteration 1
Worker Task 7 is on iteration 1
`Red`: iteration 1
Worker Task 4 is on iteration 2
`Octarine`: iteration 2
Worker Task 5 is on iteration 2
`Black`: iteration 2
Worker Task 6 is on iteration 2
`White`: iteration 2
Worker Task 7 is on iteration 2
`Red`: iteration 2
Worker Task 4 is on iteration 3
`Octarine`: iteration 3
Worker Task 5 is on iteration 3
`Black`: iteration 3
Worker Task 6 is on iteration 3
`White`: iteration 3
Worker Task 7 is on iteration 3
`Red`: iteration 3
Worker Task 4 is on iteration 4
`Octarine`: iteration 4
Worker Task 5 is on iteration 4
`Black`: iteration 4
Worker Task 6 is on iteration 4
`White`: iteration 4
Worker Task 7 is on iteration 4
`Red`: iteration 4
Worker Task 4 is on iteration 5
`Octarine`: iteration 5
Worker Task 5 is on iteration 5
`Black`: iteration 5
Worker Task 6 is on iteration 5
`White`: iteration 5
Worker Task 7 is on iteration 5
`Red`: iteration 5
Worker Task 8 is on iteration 1
`Green`: iteration 1
Worker Task 9 is on iteration 1
`Blue`: iteration 1
Worker Task 10 is on iteration 1
`Octarine`: iteration 1
Worker Task 11 is on iteration 1
`Black`: iteration 1
Worker Task 8 is on iteration 2
`Green`: iteration 2
Worker Task 9 is on iteration 2
`Blue`: iteration 2
Worker Task 10 is on iteration 2
`Octarine`: iteration 2
Worker Task 11 is on iteration 2
`Black`: iteration 2
Worker Task 8 is on iteration 3
`Green`: iteration 3
Worker Task 9 is on iteration 3
`Blue`: iteration 3
Worker Task 10 is on iteration 3
`Octarine`: iteration 3
Worker Task 11 is on iteration 3
`Black`: iteration 3
Worker Task 8 is on iteration 4
`Green`: iteration 4
Worker Task 9 is on iteration 4
`Blue`: iteration 4
Worker Task 10 is on iteration 4
`Octarine`: iteration 4Worker Task
11 is on iteration 4
`Black`: iteration 4
Worker Task 8 is on iteration 5
`Green`: iteration 5
Worker Task 9 is on iteration 5
`Blue`: iteration 5
Worker Task 10 is on iteration Worker Task 511
 is on iteration `Octarine5`: iteration
5`
Black`: iteration 5
Worker Task 12 is on iteration 1
`White`: iteration 1
Worker Task 13 is on iteration 1
`Red`: iteration 1
Worker Task Worker Task 1415 is on iteration  is on iteration 11

``GreenBlue`: iteration `: iteration 11

Worker Task 12 is on iteration 2
`White`: iteration 2
Worker Task 13 is on iteration 2
`Red`: iteration 2
Worker Task Worker Task 14 is on iteration 152 is on iteration
2`
Green``: iteration Blue2`: iteration
2
Worker Task 12 is on iteration 3
`White`: iteration 3
Worker Task 13 is on iteration 3
`Red`: iteration 3
Worker Task Worker Task 14 is on iteration 153
` is on iteration Green`: iteration 33

`Blue`: iteration 3
Worker Task 12 is on iteration 4
`White`: iteration 4
Worker Task 13 is on iteration 4
`Red`: iteration 4
Worker Task Worker Task 14 is on iteration 154 is on iteration
4`
Green``: iteration Blue4`: iteration
4
Worker Task 12 is on iteration 5
`WhiteWorker Task 13 is on iteration `: iteration 55

`Red`: iteration 5
Worker Task Worker Task 14 is on iteration 155 is on iteration
5`Green`: iteration
5`
Blue`: iteration 5
Worker Task 16 is on iteration Worker Task 117
 is on iteration `1Octarine
`: iteration `1Black
`: iteration 1
Worker Task Worker Task 18 is on iteration 191 is on iteration
1`White
`: iteration `1Red
`: iteration 1
Worker Task Worker Task 1617 is on iteration 2 is on iteration 2

``BlackOctarine`: iteration `: iteration 2
2
Worker Task Worker Task 1819 is on iteration 2 is on iteration
`2White
`: iteration `2Red
`: iteration 2
Worker Task Worker Task 1617 is on iteration  is on iteration 33

``Black`: iteration Octarine`: iteration 3
3
Worker Task Worker Task 1819 is on iteration  is on iteration 3
`3White
``: iteration Red3
`: iteration 3
Worker Task Worker Task 1617 is on iteration  is on iteration 44

``OctarineBlack`: iteration `: iteration 44

Worker Task Worker Task 1819 is on iteration  is on iteration 44

``RedWhite`: iteration `: iteration 44

Worker Task Worker Task 1617 is on iteration 5 is on iteration
`5
`Octarine`: iteration Black5
`: iteration 5
Worker Task Worker Task 1819 is on iteration 5 is on iteration
`5
`WhiteRed`: iteration `: iteration 5
5
Worker Task Worker Task 2021 is on iteration  is on iteration 11

``GreenBlue`: iteration `: iteration 11

Worker Task Worker Task 22 is on iteration 231 is on iteration 1

`Black``: iteration Octarine1`: iteration
1
Worker Task Worker Task 2021 is on iteration  is on iteration 22

``GreenBlue`: iteration `: iteration 22

Worker Task Worker Task 2322 is on iteration  is on iteration 2
2`
Black``: iteration Octarine2`: iteration
2
Worker Task 20 is on iteration Worker Task 321
 is on iteration `3Green
`: iteration `3Blue
`: iteration 3
Worker Task Worker Task 23 is on iteration 223 is on iteration 3

``BlackOctarine`: iteration `: iteration 33

Worker Task Worker Task 2021 is on iteration  is on iteration 44

``GreenBlue`: iteration `: iteration 44

Worker Task Worker Task 23 is on iteration 224 is on iteration
4`
Black``: iteration Octarine4`: iteration
4
Worker Task Worker Task 2021 is on iteration  is on iteration 55
`Green`: iteration 5

`Blue`: iteration 5
Worker Task Worker Task 23 is on iteration 225 is on iteration
5`
Black``: iteration Octarine5`: iteration
5
Worker Task 24 is on iteration 1
Worker Task `25 is on iteration 1
White`: iteration `1Red
`: iteration 1
Worker Task 26 is on iteration 1
`Green`: iteration Worker Task 127
 is on iteration 1
`Blue`: iteration 1
Worker Task Worker Task 2425 is on iteration  is on iteration 22

``WhiteRed`: iteration `: iteration 22

Worker Task 26 is on iteration 2
`Green`: iteration 2
Worker Task 27 is on iteration 2
`Blue`: iteration 2
Worker Task Worker Task 2425 is on iteration  is on iteration 33

``WhiteRed`: iteration `: iteration 33

Worker Task 26 is on iteration 3
`Green`: iteration 3
Worker Task 27 is on iteration 3
`Blue`: iteration 3
Worker Task Worker Task 2425 is on iteration  is on iteration 44

``WhiteRed`: iteration `: iteration 44

Worker Task 26 is on iteration 4
`Green`: iteration 4
Worker Task 27 is on iteration 4
`Blue`: iteration 4
Worker Task Worker Task 2425 is on iteration  is on iteration 55

``WhiteRed`: iteration `: iteration 55

Worker Task 26 is on iteration 5
`Green`: iteration 5
Worker Task 27 is on iteration 5
`Blue`: iteration 5
Worker Task 28Worker Task  is on iteration 291 is on iteration
1`
Octarine``: iteration Black1
`: iteration 1
Worker Task 28Worker Task  is on iteration 292 is on iteration
2`
Octarine``: iteration Black2`: iteration
2
Worker Task Worker Task 2829 is on iteration  is on iteration 33

``OctarineBlack`: iteration `: iteration 33

Worker Task Worker Task 2829 is on iteration  is on iteration 44

``OctarineBlack`: iteration `: iteration 44

Worker Task Worker Task 2829 is on iteration  is on iteration 55

``OctarineBlack`: iteration `: iteration 55


#SOA Struct Layout
2
Vector3{x = 1.000, y = 4.000, z = 9.000}
1.000
0x820691BC0
Vector3{x = 2.000, y = 3.000, z = 4.000}
[Vector3{x = 1.000, y = 4.000, z = 9.000}, Vector3{x = 2.000, y = 3.000, z = 4.000}]
2
Vector3{x = 1.000, y = 4.000, z = 9.000}
1.000
0x820691A00
Vector3{x = 2.000, y = 3.000, z = 4.000}
1.000
[Vector3{x = 1.000, y = 4.000, z = 9.000}, Vector3{x = 2.000, y = 3.000, z = 4.000}]
[Vector3{x = 1.000, y = 4.000, z = 9.000}, Vector3{x = 2.000, y = 3.000, z = 4.000}]
[Vector3{x = 1, y = 4, z = 9.000}, Vector3{x = 0, y = 0, z = 0.000}, Vector3{x = 0, y = 0, z = 0.000}]
1
[Vector3{x = 0, y = 0, z = 0.000}]
[Vector3{x = 1, y = 2, z = 3.000}, Vector3{x = 4, y = 5, z = 9.000}, Vector3{x = -4, y = -4, z = 3.000}]
3
8
[Vector3{x = 1, y = 2, z = 3.000}, Vector3{x = 4, y = 5, z = 9.000}, Vector3{x = -4, y = -4, z = 3.000}]

soa_zip and soa_unzip
{a = 1, b = 2.000, c = true} 0
1 2.000 true
{a = 3, b = 4.000, c = false} 1
3 4.000 false
{a = 9, b = 16.000, c = true} 2
9 16.000 true
[1, 3, 9] [2.000, 4.000, 16.000] [true, false, true]

#constant literal expressions
1
2
Bar{x = 3.000, y = 4.000}
3.000
4.000
3.000
4.000
-------
1
4
9
-------
0.000
-------
1
1
1
16
-------
1
1
1
16
-------
72
108
108
Hello
lope

#union #maybe
123 0x820691BC7
123 0x820691BC7
0x0 false
0x820691BC7 true

#explicit context definition
dummy_procedure

#relative data types
123
[1, 2, 3]
[1, 2, 3]
2

#'or_else'

#'or_return'

# core:math/big
Random Prime A: 8320520649292610833 (base: 10, bits: 63, digits: 2)
Random number iterations until prime found: 49

Packed into u32 buf: [1331920145, 1937272178] | err: Okay | written: 2

Packed into buf of 6-bit bytes: [17, 52, 55, 24, 15, 9, 23, 27, 56, 13, 7] | err: Okay | written: 11

2048 bit random number: 10831192313550861925009037586508611699874583713078748010146305388728625648152219907609815137658818123700797542459094621689898990029751171709885070245266278365372383201652231056595712724421992414837745148235846959605227207365108802175420988614731266615583392030572856147912596385534918913661270199213044167621348293364978701079603101664943777249630483661604774476072708783048998679420395113760550890048383688584321450046652643105590042630816597629021302300783200894518906426573735743548208006933154512285707488103344666361078012453208783558719519938797021309928582233413828782042144763309796532854168779383272681534256 (base: 10, bits: 2047, digits: 35)

GCD of random prime A and random number B: 1 (base: 10, bits: 1, digits: 1)

LCM of random prime A and random number B (in base 36): YNEZOQBT89SLVX8ZJ2I0PRJVU5G6E22IYXQODPU1A6NXRRWFCIVOH6UKVGAG8502QWIJHTGEQL9R3E2MLHTRIBG2VHLFZ85AP2M8O01BL3YOWW08V6XO7ZRBQBH144FBYD1CLFAPE229S9MLFEZQBQU9K3695DS9GIDQFQ0OTHB28UGJ8D4UDQYY1Q59KZGF00FBT7Y6FORB5MFVQRBX12194HC0GF8UFZZ792GTSVH6FBOOIZQQQ5ASSK3UF39FO2M653XO5C913SL0BXFUBP9EMRQLVG0KVW2UDRCF66QS5RLM1MIOAOPVCCSIAFEER0IW1N6DDLCU02SI9GXYDQNFVZEWDL5I0LJ1LZM35HYVTJA3CSGYKPQLVNZUMRV74FMCLSPD2XVJGJBQ9D71XL4G (base: 36, bits: 2110, digits: 36)

# matrix type
b matrix[3.000, 0.000; 0.000, 3.000]
b == f true
a matrix[2.000, 3.000, 1.000; 4.000, 5.000, 0.000]
b matrix[1.000, 2.000; 3.000, 4.000; 5.000, 6.000]
m * v matrix[35.000; 52.000; 17.000; 24.000]
v * m matrix[26.000, 34.000, 47.000, 17.000]
r [16.000, 20.000, 15.000, 11.000]
a + b matrix[-4, 3; 12, -3]
a - b matrix[6, 1; -6, 11]
a & b matrix[1, 0; 1, 0]
a | b matrix[-5, 3; 11, -3]
a ~ b matrix[-6, 3; 10, -3]
a &~ b matrix[0, 2; 2, 4]
hadamard_product(a, b) matrix[-5, 2; 27, -28]
m2 matrix[
        1.000, 3.000,
        2.000, 4.000,
]
m4 matrix[1.000, 3.000, 0.000, 0.000; 2.000, 4.000, 0.000, 0.000; 0.000, 0.000, 1.000, 0.000; 0.000, 0.000, 0.000, 1.000]
mat2(m4) matrix[1.000, 3.000; 2.000, 4.000]
b4 [1.000, 3.000, 5.000, 0.000, 2.000, 4.000, 0.000, 7.000, 0.000, 0.000, 6.000, 0.000, 0.000, 0.000, 0.000, 8.000]
x matrix[1.000, 3.000, 5.000, 7.000; 2.000, 4.000, 6.000, 8.000]
y matrix[1.000, 5.000; 2.000, 6.000; 3.000, 7.000; 4.000, 8.000]
```

### CODE REVIEW

**Comment by semarie** [comment]
could you add at least `freebsd_amd64` inside the CI ? see `.github/workflows/ci.yml` file

**Comment by semarie** [comment]
it seems to me that there are still missing pieces. I recently started to work on it, and my (unfinished) work is far larger.

you could try to run: `odin check examples/all -vet -strict-style -target:freebsd_amd64` to see the missing pieces

**Comment by Kelimion** [comment]
It's really sad that the [CI doesn't offer any BSD](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources).

**Comment by hoanga** [comment]
thank you for pointing out the larger effort for better freebsd support that appears to be already underway. since it seems like it would make more sense to base further efforts from that point in time i am going to go ahead and close this pr attempt sometime this weekend (unless this patch is helpful as is). wish i had the bandwidth currently to spend more time on this (apologies)

and it is a shame about ci support for bsds

**Review by gingerBill — APPROVED** [review]

**Pull request merged**
