### PR TITLE
trim trailing zeroes from string in io.write_f64 to prevent json dataloss

### PR DESCRIPTION
**Pull request by karl-zylinski**
When using `io.write_f64` the user has no control over the precision, so it makes sense to trim off trailing zeroes from the resulting string.

Without my changes writing `0.123` will result in `0.1230000000000000`. With my changes writing will result in `0.123`.
If you write `0.0` then it will just write `0`

Without these changes, if you write a json file (using `core:encoding/json`) and then read it back, you may run into trouble due to `io.write_f64` writing lots of trailing zeroes and `strconv.parse_f64_prefix` loosing precision due to taking all those trailing zeroes into consideration. I.e. writing and reading json back and forth will make values drift over time due to the trailing zeroes written and read, essentially resulting in data loss.

Small test program with comments that show how the result is differs with and without my changes:
```
package f64_trim

import "core:strings"
import "core:fmt"
import "core:io"

main :: proc() {
    b, _ := strings.builder_make(context.temp_allocator)
    some_float: f64 = 0.123

    // We have no control of the precision of write_f64. Therefore I have made
    // so that it trims off trailing zeroes from the result.
    io.write_f64(strings.to_writer(&b), f64(some_float))

    // Without my changes, it prints: 0.1230000000000000
    // With my changes, it prints: 0.123
    fmt.println(strings.to_string(b))
}
```

Note: Initially this PR had changes to `parse_f64_prefix`, removing trailing zeroes from the input string, which lessened the precision loss from those trailing zeroes. But that wasn't really necessary for my uses and also a bit scary, so I removed that part.

### CODE REVIEW

**Comment by flysand7** [comment]
well from what i see odin's float parsing is not precise to begin with

**Comment by karl-zylinski** [comment]
@flysand7 this is true, perhaps I should stick to only doing the trimming of the written stuff, since that fixes the json issues without doing scary things to the parser 🤔

**Comment by karl-zylinski** [comment]
I removed the trailing zeroes trimming from parse_f64_prefix, since it wasn't strictly necessary.

**Comment by karl-zylinski** [comment]
@gingerBill @Kelimion I find working with JSON is more or less broken without something like this fix, you just need to write, read and write json again for many floats to get big differences compared to originally written value.

**Comment by karl-zylinski** [comment]
Closing this because https://github.com/odin-lang/Odin/pull/3847 solves this in a more elegant way, and it also works for `fmt.printfln` etc.

**Pull request closed without merging**
