### PR TITLE
os_linux additions + libc to syscalls

### PR DESCRIPTION
**Pull request by jasonKercher**
I added `rename`, `remove`, `make_directory`, `remove_directory`, `is_dir`, `is_file` to match `core/os/file_windows.odin`, so now `odinfmt` can will compile on Linux!

I moved a handful of libc calls to straight syscalls.  So far, I was only able to test on amd64, but it should be able to handle arm64, arm and i386 as well. If someone wants to test that on a different arch, here is a quick test program:

```odin
package main

import "core:testing"
import "core:os"

@test
test_os_linux :: proc(t: ^testing.T) {
        err: os.Errno
        fd: os.Handle
        n: int

        mybytes : [4]u8 = "fgkc"

        err = os.make_directory("temp")
        testing.expect_value(t, err, 0)
        testing.expect(t, os.is_dir("temp"))
        testing.expect(t, !os.is_file("temp"))

        /* try to open bad path */
        fd, err = os.open("dir/that/doesnt/exist.txt", os.O_WRONLY, 0o666)
        testing.expect_value(t, fd, -1)
        testing.expect(t, err != 0)

        /* open new file for writing */
        fd, err = os.open("temp/shnt.txt", os.O_CREATE | os.O_TRUNC | os.O_WRONLY, 0o666)
        testing.expect(t, fd != -1)
        testing.expect_value(t, err, 0)

        /* write some shit */
        n, err = os.write(fd, mybytes[:])
        testing.expect_value(t, n, 4)
        testing.expect_value(t, err, 0)

        /* close new file */
        err = os.close(fd)
        testing.expect_value(t, err, 0)

        /* directory not empty */
        err = os.remove_directory("temp")
        testing.expect(t, err != 0)

        /* make directory empty */
        err = os.rename("temp/shnt.txt", "shnt.txt")
        testing.expect_value(t, err, 0)
        testing.expect(t, !os.is_file("temp/shnt.txt"))

        /* NOW remove it... */
        err = os.remove_directory("temp")
        testing.expect_value(t, err, 0)

        /* check file now... */
        testing.expect(t, os.is_file("shnt.txt"))

        /* remove the file */
        err = os.remove("shnt.txt")
        testing.expect_value(t, err, 0)

        /* check for file one more time */
        testing.expect(t, !os.is_file("shnt.txt"))

}
```

### CODE REVIEW

**Comment by Platin21** [comment]
Hmm would have put the syscalls into sys/linux and called them from os. But yeah

**Comment by jasonKercher** [comment]
> Hmm would have put the syscalls into sys/linux and called them from os. But yeah

If that is preferred, I can change it.  I didn't want to break any existing code that is calling `_unix_*` from `os` which are links into libc.  It is a bit ambiguous currently and there is a bit of goofiness with `errno` in libc vs calculating it from the syscall return.

**Comment by Platin21** [comment]
Ohh i meant because we want to move to a new os library anyways and normal os will be deprecated so i though it would be a good idea to move it over. 

Yeah i wouldn’t touch the unix stuff just put it in sys/linux makes more sense. Especially as the unix stuff isn’t necessarily correct anyways. As different platforms seem to have different error returns and values even sometimes.

So overall maybe better to have it working in os2 and leaving os just for compatibility reasons. But just my thinking..

**Comment by jasonKercher** [comment]
Ah okay.  I see that.  os2 is pretty incomplete, but I can see the general idea is to merge the different platforms under a one umbrella.  I will move the syscall code to sys, and move new os stuff to os2.  I just want to keep the *new* functions so `odinfmt` can compile for Linux.  Currently, `odinfmt` uses `rename`, `remove`, `is_dir`, `is_file` and they only exist in `*_windows.odin` files.

**Comment by Platin21** [comment]
Ahh makes sense

**Pull request merged**
