### PR TITLE
Fix `absolute_path_from_handle` on OSX

### LINKED ISSUE #1143: `absolute_path_from_handle` does not work on OSX
## Context

[absolute_path_from_handle](https://github.com/odin-lang/Odin/blob/ca33cb990b5a05829067e18ea24bcb36a75aba67/core/os/os_darwin.odin#L489) is making use of `/proc/...` entries for reading file descriptors.
This does not exist at all in current OSX.

* Operating System: OSX 10.15
* Please paste `odin version` output: `odin version dev-2021-09:d4f5ef04`

### PR DESCRIPTION
**Pull request by rasa-silva**
Seems to fix #1143 but please comment since I have no idea if this is the correct way to go about this...

### CODE REVIEW

**Comment by Kelimion** [comment]
Could you fix this, please? Other than that, thanks for the work in figuring this out.
```
Run ./odin check examples/demo/demo.odin -vet
/Users/runner/work/Odin/Odin/core/os/os_darwin.odin(9:8) 'strconv' declared but not used
```

**Comment by rasa-silva** [comment]
Updated.

**Comment by Kelimion** [comment]
It prints garbage :-(

This does work:
```odin

absolute_path_from_handle :: proc(fd: os.Handle) -> (string, os.Errno) {
	buf : [256]byte
	res  := os._unix_fcntl(fd, os.F_GETPATH, &buf[0])
	if	res != 0 {
		return "", os.Errno(os.get_last_error())
	}

	path := strings.clone_from_cstring(cstring(&buf[0]), context.temp_allocator)
	return path, os.ERROR_NONE
}
```

**Comment by rasa-silva** [comment]
Updated with suggested fix.

**Pull request merged**
