### PR TITLE
Add start and end parameters to string.index and index_byte functions. 

### PR DESCRIPTION
**Pull request by hodgka**
Might be nice to have start and end parameters for strings.index, similar to [str.find in python](https://docs.python.org/3/library/stdtypes.html#str.find).

### CODE REVIEW

**Comment by laytan** [comment]
I believe this has been suggested before and the person was then pointed to slices making this pretty trivial in Odin:
```odin
i := start + strings.index(str[start:end])
```

**Comment by hodgka** [comment]
Fair enough. Feel free to close

**Comment by gingerBill** [comment]
Why did you not just make a new procedure? Why did you change a pre-existing one which many people might rely on the signature?

**Comment by hodgka** [comment]
I figured it doesn't change the present usage of `strings.index(haystack, needle)`, and doesn't add additional API surface. Does this actually break the existing API somehow? I'm still fairly new to odin, so pardon me if I'm misunderstanding

I could just split it out as like laytan suggested, 
```
index_with_bounds :: proc(haystack, needle: string, start, end: int) {
	return  start + strings.index(haystack[start:end], needle)
}
```

**Pull request closed without merging**
