### PR TITLE
build: add llvm18 support

### PR DESCRIPTION
**Pull request by chenrui333**
- https://github.com/Homebrew/homebrew-core/pull/171372

cc @laytan

### CODE REVIEW

**Comment by laytan** [comment]
This is a weird one? Why would we need to change things here?

We don't want to run on the latest and greatest llvm in our ci because we also support older versions, and generally wait a bit on upgrading CI/releases.

**Comment by chenrui333** [comment]
> This is a weird one? Why would we need to change things here?

to match with the homebrew build?

**Comment by chenrui333** [comment]
what is the concern here?

**Comment by laytan** [comment]
> > This is a weird one? Why would we need to change things here?
> 
> to match with the homebrew build?

Alright, but for the reasons I stated in the last comment we don't necessarily want that.

**Comment by chenrui333** [comment]
that is fine, let's do matrix build

---

note, this is some common practice I am doing to build alliance between upstream and downstream/homebrew

**Comment by laytan** [comment]
I would be fine with a matrix, I don't have final say here though

**Comment by chenrui333** [comment]
updated to use the matrix build

**Pull request closed without merging**
