### PR TITLE
Add's Handling for Return Values for Linker-Stage

### PR DESCRIPTION
**Pull request by Platin21**
I added return values so that if the linker fails it also gets reflected in the return value of the program. 
Tried to use gb_exit and exit but zsh behaved weird with both of them. 

This is related to #895

### CODE REVIEW

**Review by gingerBill — APPROVED** [review]

**Comment by Platin21** [comment]
This will show the current macOS error that happens because of some linking bug.

**Comment by Platin21** [comment]
And it did exactly what I expected 👍

**Comment by gingerBill** [comment]
Perfect!

**Comment by Platin21** [comment]
Doesn't look like it changed can we re-run this.

**Comment by Platin21** [comment]
Ok looks good now with that change. Do we still want this? @ThisDrunkDane though it was already in the compiler that when the linker fails it returns the codes.

**Pull request merged**
