### PR TITLE
Add glfw.GetCocoaWindow

### PR DESCRIPTION
**Pull request by janivanecky**

### CODE REVIEW

**Comment by Kelimion** [comment]
To avoid this error, you'd have to break `native.odin` into OS-specific files.
e.g. `native_windows.odin` with `//+build windows` at the top,
`native_darwin.odin` + `//+build darwin`,
`native_linux.odin` + `//+build linux`.

**Comment by janivanecky** [comment]
Thanks! Updated.

**Comment by Kelimion** [comment]
You no longer need the `when ODIN_OS == .Darwin`, et al, because the `_darwin.odin` and `//+build darwin` already preclude those files from being processed on other operating systems. Looks good otherwise.

**Comment by janivanecky** [comment]
Gotcha, updated.

**Pull request merged**
