### PR TITLE
Added a number of linux syscalls

### PR DESCRIPTION
**Pull request by corruptmemory**
Reformatted some of the file.

Added:
* remove
* rename
* mmap
* munmap
* ftruncate

### CODE REVIEW

**Comment by Kelimion** [comment]
There are a lot of indentation changes, including in parts of the file that are supposedly unchanged.
Odin's default style uses tabs for indentation and spaces for alignment.

**Comment by corruptmemory** [comment]
ok. I can change back to tabs.

Ugh, tabs.

:grin:

**Comment by corruptmemory** [comment]
Soo... this is kind of messy.

master:
```
// These and above do not use tabs
EPROTOTYPE:     Errno : 91	/* Protocol wrong type for socket */
ENOPROTOOPT:    Errno : 92	/* Protocol not available */
EPROTONOSUPPORT:Errno : 93	/* Protocol not supported */
ESOCKTNOSUPPORT:Errno : 94	/* Socket type not supported */
// These and below use tabs
EOPNOTSUPP: 	Errno : 95	/* Operation not supported on transport endpoint */
EPFNOSUPPORT: 	Errno : 96	/* Protocol family not supported */
EAFNOSUPPORT: 	Errno : 97	/* Address family not supported by protocol */
EADDRINUSE: 	Errno : 98	/* Address already in use */
EADDRNOTAVAIL: 	Errno : 99	/* Cannot assign requested address */
ENETDOWN: 		Errno : 100	/* Network is down */
ENETUNREACH: 	Errno : 101	/* Network is unreachable */
ENETRESET: 		Errno : 102	/* Network dropped connection because of reset */
```

I did `tabify` with a `tab-width` of 4 in Emacs.  We now have uniform tab use, but there are still whitespace changes.

Using the latest MR will make the use of table uniform, but will add whitespace changes to the diffs.

Or I can redo the patch and leave the file in "mixed spaces" mode.

**Comment by Kelimion** [comment]
> Soo... this is kind of messy.
> 
> I did `tabify` with a `tab-width` of 4 in Emacs. We now have uniform tab use, but there are still whitespace changes.
> Using the latest MR will make the use of table uniform, but will add whitespace changes to the diffs.
> 
> Or I can redo the patch and leave the file in "mixed spaces" mode.

Right. That's kinda why we use spaces to line things up. Main problem is with GitHub using 8-space tabs, so if you're used to 4-space tabs, things may sometimes slip through and look fine locally but a tad wonky on GH.

**Comment by corruptmemory** [comment]
Right, this is what is in `os_linux.odin` on master.  Some things were aligned with only spaces others with spaces and tabs.

image


In any case, I just rebuilt my changes off of what was in master.  Now the diffs are what one would expect.

**Comment by gingerBill** [comment]
`package os` is a complete mess at the moment and does need to be completely rewritten. `package os2` is meant to be the mockup of that rewrite. 

This means `package os` ought not to have ANY platform specific declarations, and be completely platform agnostic in terms of its interface.

**Comment by corruptmemory** [comment]
OK.  Is this mockup in a state where one can sensibly contribute?

As you can see from this PR I was adding some file and mmap stuff.  If there is a stable place I can move it I'm happy to do so.

**Pull request closed without merging**
