### PR TITLE
Fix `text/table` using `len()` for strings

### LINKED ISSUE #3432: text/table uses bytes instead of runes for length
## Context
The `text/table` library is using `len` where `utf8.rune_count` would probably be more appropriate. See the following program and its output.

```odin
package main

import "core:os"
import "core:text/table"

main :: proc() {
    t: table.Table
    table.init(&t)
    table.caption(&t, "Tɛst")
    table.row(&t, "Hellope!")
    table.row(&t, "Hɛllope!")

    stdout := os.stream_from_handle(os.stdout)
    table.write_ascii_table(stdout, &t)
}
```

The `ɛ` is a two-byte UTF-8 rune here.

## Result
```
+---------+
|  Tɛst  |
+---------+
|Hellope! |
|Hɛllope!|
+---------+
```

## Expected
```
+--------+
|  Tɛst  |
+--------+
|Hellope!|
|Hɛllope!|
+--------+
```

### PR DESCRIPTION
**Pull request by Feoramund**
Fixes #3432

### CODE REVIEW

**Comment by gingerBill** [comment]
Note that because the procedure was named `write_ascii_table`, you will need change its name to better reflect these changes.

**Comment by oskarnp** [comment]
> Note that because the procedure was named `write_ascii_table`, you will need change its name to better reflect these changes.

The name is OK if we redefine it as referring to the delimiter characters used, as opposed to something like Unicode box-drawing characters, for example.

I'll review and test it later today.

**Comment by oskarnp** [comment]
I would reject this PR because it doesn't really solve much. See my comment in https://github.com/odin-lang/Odin/issues/3432#issuecomment-2057519705.

**Review by oskarnp — COMMENTED** [review]
I would reject this PR because it doesn't really solve much. See my comment in https://github.com/odin-lang/Odin/issues/3432#issuecomment-2057519705.

**Pull request closed without merging**
