### PR TITLE
Fix #2637

### LINKED ISSUE #2637: testing.expect_value can't compare nils
## Context
* Operating System & Odin Version: Linux, Odin: dev-2023-07:3072479c

## Expected Behavior

testing.expect_value should succeed with two nils as inputs

## Current Behavior

testing.expect_value don't consider two nils as equal

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

```
  Foo :: Maybe(string)
  x: Foo
  testing.expect(t, x == nil) // Succeeds
  testing.expect_value(t, x, nil) // Fails, "expected nil, got nil"
```

### PR DESCRIPTION
**Pull request by ramn**
where testing.expect_value can't compare nils

### CODE REVIEW

**Comment by Kelimion** [comment]
Very good catch. Thanks for the fix and regression test.

**Comment by Kelimion** [comment]
This error is a simple fix. We test the core library with `-vet -strict-style`.
```
D:/a/Odin/Odin/core/testing/testing.odin(7:8) 'reflect' declared but not used
	import "core:reflect"
	       ^
Error: Process completed with exit code 1.
```

**Comment by ramn** [comment]
> 

But reflect is used

**Comment by Kelimion** [comment]
> 

Correct, but they're being used from within a polymorphic procedure and there's no visible specialization that `-vet` can see. To tell `-vet` to shut up, you can do the following:
```odin
import "core:reflect"
_ :: reflect // alias reflect to nothing to force visibility for -vet
```

**Comment by ramn** [comment]
Aha thanks for the explanation

**Comment by Kelimion** [comment]
> Aha thanks for the explanation

Another option would've been:
```odin
is_nil :: reflect.is_nil
```
And then using the aliased `is_nil` without the reflect prefix in the parapoly, because it is again a name visible to the vetter.

**Pull request merged**
