### PR TITLE
Reordered OS on items.

### PR DESCRIPTION
**Pull request by milrope**
To make it alphabetically ordered. Actually to list free software OS first.

### CODE REVIEW

**Comment by milrope** [comment]
why you have closed this PR? Did i make any mistake?

**Comment by milrope** [comment]
@ThisDrunkDane hello.

**Comment by ThisDrunkDane** [comment]
There is no need for this change, most of our users are on Windows so it makes sense to have the instructions for that first.

**Comment by gingerBill** [comment]
Reordering for just the sake of having Free Open Source Software (FOSS) first is not worth a change for the sake of it.

And I do not condone FOSS Zealotry.

Please don't make another PR for something similar, which are doing across many other repositories.

**Comment by milrope** [comment]
That sucks. I am sorry.
But how do you know that most of Odin users are on Windows?

**Comment by milrope** [comment]
@gingerBill I am sorry.

But you don't?

**Comment by gingerBill** [comment]
@milrope As I said, I do not condone FOSS Zealotry. Of which, you are partaking in a lot across numerous repositories, not just this one.

**Comment by milrope** [comment]
What if i only told you that I did it to alphabetically ordering the list items. will you then noticethat some how GNU/Linux becomes first and windows become last?

**Comment by gingerBill** [comment]
@milrope Forgive my bluntness, bu as I said, I do not condone FOSS Zealotry. I don't believe you because of your past actions. 

And as @ThisDrunkDane stated, most people using Odin are on Windows, and having the most popular platform first is more useful than having it be alphabetical for the time being.

**Comment by milrope** [comment]
okay, you do your business. I am out. sorry.

**Pull request closed without merging**
