### PR TITLE
List the supported targets using `odin build . -targets:?`

### PR DESCRIPTION
**Pull request by bayo-code**
Added support for listing supported targets using `odin targets`.

### CODE REVIEW

**Comment by Kelimion** [comment]
This is asymmetric with `odin build . -microarch:?` and `-target-features:?`

**Comment by bayo-code** [comment]
What do I need to add, please?

I'm new to the project, and I'm still trying to find my way around the code.

**Comment by FourteenBrush** [comment]
I mean `odin build` prints the available targets when you attempt to do something like `odin build . -target:something-invalid`, but having it support `-target:?` doesn't sound bad.

Perhaps this could help?
https://github.com/odin-lang/Odin/blob/da196a2b74f58be1762d496942fea83371c96d03/src/main.cpp#L3280-L3310

**Comment by bayo-code** [comment]
Ah, yes this makes sense now... I think I can do this 🙂

**Pull request merged**
