### PR TITLE
Link as PIE for PIC by default

### LINKED ISSUE #4448: [ENH] Link as PIE for PIC by default
##  Problem

I'm using termux and when I'm running any executable compiled with odin, I get
```
"./main.out": error: Android 5.0 and later only support position-independent executables (-fPIE).
```

It's not hard to see that odin uses `-no-pie` to compile the program, thus we get the error:
```
odin build examples/demo -reloc-mode:pic -print-linker-flags
clang -Wno-unused-command-line-argument "/data/data/com.termux/files/home/repos/Odin/demo.o"  -o "/data/data/com.termux/files/home/repos/Odin/demo"  -lm -lc   -L/ -lpthread        -no-pie -Wl,-rpath,\$ORIGIN
```

##  Solution

It should be possible to directly manipulate, whether we are getting PIE or not.

### PR DESCRIPTION
**Pull request by 0dminnimda**
Closes #4448

### CODE REVIEW

**Comment by 0dminnimda** [comment]
> Position Independent executables may be created from PIC or PIE objects (.o) and PIC or PIE static libraries (.a)

Not sure how to create PIE object, so will have a limited scope of linking only PIC objects/libraries.
 
Also I just realized, we need to check that the objects are PIC, otherwise you'll see this (which actually is not too bad):
```
$ odin build examples/demo -link-pie:yes
ld.lld: error: relocation R_AARCH64_ABS64 cannot be used against local symbol; recompile with -fPIC
>>> defined in /data/data/com.termux/files/home/repos/Odin/demo.o
>>> referenced by odin_package
>>>               /data/data/com.termux/files/home/repos/Odin/demo.o:(.rodata+0x290)

ld.lld: error: relocation R_AARCH64_ABS64 cannot be used against local symbol; recompile with -fPIC
>>> defined in /data/data/com.termux/files/home/repos/Odin/demo.o
>>> referenced by odin_package
>>>               /data/data/com.termux/files/home/repos/Odin/demo.o:(.rodata+0x298)

ld.lld: error: relocation R_AARCH64_ABS64 cannot be used against local symbol; recompile with -fPIC
>>> defined in /data/data/com.termux/files/home/repos/Odin/demo.o
>>> referenced by odin_package
>>>               /data/data/com.termux/files/home/repos/Odin/demo.o:(.rodata+0x2A0)

ld.lld: error: relocation R_AARCH64_ABS64 cannot be used against local symbol; recompile with -fPIC
>>> defined in /data/data/com.termux/files/home/repos/Odin/demo.o
>>> referenced by odin_package
>>>               /data/data/com.termux/files/home/repos/Odin/demo.o:(.rodata+0x2A8)

ld.lld: error: relocation R_AARCH64_ABS64 cannot be used against local symbol; recompile with -fPIC
>>> defined in /data/data/com.termux/files/home/repos/Odin/demo.o
>>> referenced by odin_package
>>>               /data/data/com.termux/files/home/repos/Odin/demo.o:(.rodata+0x2B0)

ld.lld: error: relocation R_AARCH64_ABS64 cannot be used against local symbol; recompile with -fPIC
>>> defined in /data/data/com.termux/files/home/repos/Odin/demo.o
>>> referenced by odin_package
>>>               /data/data/com.termux/files/home/repos/Odin/demo.o:(.rodata+0x2B8)

ld.lld: error: relocation R_AARCH64_ABS64 cannot be used against local symbol; recompile with -fPIC
>>> defined in /data/data/com.termux/files/home/repos/Odin/demo.o
>>> referenced by odin_package
>>>               /data/data/com.termux/files/home/repos/Odin/demo.o:(.rodata+0x2C0)

ld.lld: error: relocation R_AARCH64_ABS64 cannot be used against local symbol; recompile with -fPIC
>>> defined in /data/data/com.termux/files/home/repos/Odin/demo.o
>>> referenced by odin_package
>>>               /data/data/com.termux/files/home/repos/Odin/demo.o:(.rodata+0x2C8)

ld.lld: error: relocation R_AARCH64_ABS64 cannot be used against local symbol; recompile with -fPIC
>>> defined in /data/data/com.termux/files/home/repos/Odin/demo.o
>>> referenced by odin_package
>>>               /data/data/com.termux/files/home/repos/Odin/demo.o:(.rodata+0x2D0)

ld.lld: error: relocation R_AARCH64_ABS64 cannot be used against local symbol; recompile with -fPIC
>>> defined in /data/data/com.termux/files/home/repos/Odin/demo.o
>>> referenced by odin_package
>>>               /data/data/com.termux/files/home/repos/Odin/demo.o:(.rodata+0x2D8)

ld.lld: error: relocation R_AARCH64_ABS64 cannot be used against local symbol; recompile with -fPIC
>>> defined in /data/data/com.termux/files/home/repos/Odin/demo.o
>>> referenced by odin_package
>>>               /data/data/com.termux/files/home/repos/Odin/demo.o:(.rodata+0x2E0)

ld.lld: error: relocation R_AARCH64_ABS64 cannot be used against local symbol; recompile with -fPIC
>>> defined in /data/data/com.termux/files/home/repos/Odin/demo.o
>>> referenced by odin_package
>>>               /data/data/com.termux/files/home/repos/Odin/demo.o:(.rodata+0x2E8)

ld.lld: error: relocation R_AARCH64_ABS64 cannot be used against local symbol; recompile with -fPIC
>>> defined in /data/data/com.termux/files/home/repos/Odin/demo.o
>>> referenced by odin_package
>>>               /data/data/com.termux/files/home/repos/Odin/demo.o:(.rodata+0x2F0)

ld.lld: error: relocation R_AARCH64_ABS64 cannot be used against local symbol; recompile with -fPIC
>>> defined in /data/data/com.termux/files/home/repos/Odin/demo.o
>>> referenced by odin_package
>>>               /data/data/com.termux/files/home/repos/Odin/demo.o:(.rodata+0x2F8)

ld.lld: error: relocation R_AARCH64_ABS64 cannot be used against local symbol; recompile with -fPIC
>>> defined in /data/data/com.termux/files/home/repos/Odin/demo.o
>>> referenced by odin_package
>>>               /data/data/com.termux/files/home/repos/Odin/demo.o:(.rodata+0x300)

ld.lld: error: relocation R_AARCH64_ABS64 cannot be used against local symbol; recompile with -fPIC
>>> defined in /data/data/com.termux/files/home/repos/Odin/demo.o
>>> referenced by odin_package
>>>               /data/data/com.termux/files/home/repos/Odin/demo.o:(.rodata+0x308)

ld.lld: error: relocation R_AARCH64_ABS64 cannot be used against local symbol; recompile with -fPIC
>>> defined in /data/data/com.termux/files/home/repos/Odin/demo.o
>>> referenced by odin_package
>>>               /data/data/com.termux/files/home/repos/Odin/demo.o:(.rodata+0x310)

ld.lld: error: relocation R_AARCH64_ABS64 cannot be used against local symbol; recompile with -fPIC
>>> defined in /data/data/com.termux/files/home/repos/Odin/demo.o
>>> referenced by odin_package
>>>               /data/data/com.termux/files/home/repos/Odin/demo.o:(.rodata+0x318)

ld.lld: error: relocation R_AARCH64_ABS64 cannot be used against local symbol; recompile with -fPIC
>>> defined in /data/data/com.termux/files/home/repos/Odin/demo.o
>>> referenced by odin_package
>>>               /data/data/com.termux/files/home/repos/Odin/demo.o:(.rodata+0x320)

ld.lld: error: relocation R_AARCH64_ABS64 cannot be used against local symbol; recompile with -fPIC
>>> defined in /data/data/com.termux/files/home/repos/Odin/demo.o
>>> referenced by odin_package
>>>               /data/data/com.termux/files/home/repos/Odin/demo.o:(.rodata+0x328)

ld.lld: error: too many errors emitted, stopping now (use --error-limit=0 to see all errors)
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Though I guess you are never shielded from loading a third party library, and only the user is responsible for how it's compiled, so not sure if it's useful to gatekeep the user only for the case where the object files are generated by odin.

**Comment by avanspector** [comment]
Maybe reusing `-reloc-mode` flags would be better to enable this feature? (The flag doesn't affect the linker right now, but llvm produces the correct code regardless). Just make `-reloc-mode:pie` remove `-no-pie` from linker flags?

**Comment by 0dminnimda** [comment]
Pie is not the same as pic, although very similar. Your suggestion will work for my case, but isn't the idea is give the user more control, not less?

**Comment by avanspector** [comment]
What are the cases for PIE without PIC?

**Comment by 0dminnimda** [comment]
One LLM says there are some cases for PIE without PIC, but they are very obscure. PIC without PIE though is required for shared libraries AFAIK.
I think it's resonable to defalt to PIE for executables with reloc mode PIC, but sure about other cases. Good call, I'll make the change simpler, and further complications shall be resolved on a case by case basis.

The only consern I see is what if the user is compiling with PIC and linking non-PIC static library, but I feel comfortable to just require linked libraries to be PIC if you specify your code to be PIC. AFAIK all modern platforms support PIC, even microcontrollers.

**Comment by Kelimion** [comment]
> Maybe reusing `-reloc-mode` flag would be better to enable this feature? (The flag doesn't affect the linker right now, but llvm produces the correct code regardless). Just make `-reloc-mode:pic` remove `-no-pie` from linker flags?

I'm in favor of this solution. It's a lot more elegant. If and when we ever find the obscure use case where PIC and PIE don't go hand in glove, we can fit a more appropriate solution then.

**Comment by Kelimion** [comment]
Now we're cooking with gas. And you've verified this still fixes your #4448 issue?

**Comment by Kelimion** [comment]
Oops.
image

**Comment by 0dminnimda** [comment]
> And you've verified this still fixes your #4448 issue?

Yes, it works now

**Comment by Kelimion** [comment]
CI failure isn't your fault, but due to an intermediate commit.

**Comment by 0dminnimda** [comment]
Let's see if it will be ok now.

> intermediate commit.

I don't see any changes for `.github` folder so what changes github actions are picking up?

**Pull request merged**
