### PR TITLE
Fix misplaced line number in log (was wrongly formatted and before procedure)

### PR DESCRIPTION
**Pull request by ThisDrunkDane**
Before: `[DEBUG] --- [:176clean_field_key()]  ImGuiWindowFlags_Popup`
After: `[DEBUG] --- [clean_field_key():176]  ImGuiNavLayer_Menu`

### CODE REVIEW

**Comment by gingerBill** [comment]
It's both a bug and not a bug.

I preferred `file:line:procedure()` over `file:procedure():line`

but I didn't handle the no "file" case very well

**Comment by ThisDrunkDane** [comment]
Ah, I can change it back and fix the no file case?

**Comment by gingerBill** [comment]
Please! :)

**Comment by ThisDrunkDane** [comment]
There you go

**Comment by ThisDrunkDane** [comment]
For real this time

**Pull request merged**
