### PR TITLE
core/crypto: Add AES

### PR DESCRIPTION
**Pull request by Yawning**
- [x] 64-bit general purpose register based implementation
- [x] ECB mode
- [x] CTR mode
-  ~(Maybe) CBC mode~
- [x] GCM mode
  - [x] 64-bit general purpose register based GHASH

I am torn on supporting CBC mode or not, as it is no longer required for TLS, and the padding related issues (that the caller will need to solve) are non-trivial.  AES-NI will follow as a separate PR, since it shouldn't block "have an AES implementation".

### CODE REVIEW

**Comment by Yawning** [comment]
For what it's worth, wycheproof also thinks the GCM code is ok:
```
[INFO ] --- [2024-05-31 16:32:36] [main.odin:232:test_aead_aes_gcm()] aead/aes-gcm: ran 316, passed 197, failed 0, skipped 119
```

The skipped tests are because I am being opinionated for now and requiring 96-bit nonces per the NIST recommendation.

**Comment by Kelimion** [comment]
> For what it's worth, wycheproof also thinks the GCM code is ok:
> 
> ```
> [INFO ] --- [2024-05-31 16:32:36] [main.odin:232:test_aead_aes_gcm()] aead/aes-gcm: ran 316, passed 197, failed 0, skipped 119
> ```

I have a minor philosophical problem with the assertion that `316` tests ran, `119` of which were skipped (i.e. didn't run). So maybe `ran 197, passed 197, failed 0, skipped 119 additional tests`? Or even leave off mentioning `skipped` in that log line unless there's some way for the end user to opt in to them?

**Comment by Yawning** [comment]
> > For what it's worth, wycheproof also thinks the GCM code is ok:
> > ```
> > [INFO ] --- [2024-05-31 16:32:36] [main.odin:232:test_aead_aes_gcm()] aead/aes-gcm: ran 316, passed 197, failed 0, skipped 119
> > ```
> 
> I have a minor philosophical problem with the assertion that `316` tests ran, `119` of which were skipped (i.e. didn't run). So maybe `ran 197, passed 197, failed 0, skipped 119 additional tests`? Or even leave off mentioning `skipped` in that log line unless there's some way for the end user to opt in to them?

That's from my test-driver that lives in a separate repo, so the spew tends to be for my benefit more than anything else.  There's also logging for each test that's skipped with a reason why, that I didn't bother to paste because 119 lines of `[INFO ] --- [2024-05-31 16:40:36] [main.odin:162:test_aead_aes_gcm()] aead/aes-gcm/68: skipped, invalid nonces panic` is kind of redundant for a PR comment.

**Comment by Yawning** [comment]
I'm punting on CBC for now.  We provide ECB so it's possible to implement (decryption is parallizable so there's performance lost by using our current ECB interface) if people absolutely need it.  But using CBC in this day and age is questionable for new code.

**Pull request merged**
