### PR TITLE
add thread.pool_clear

### PR DESCRIPTION
**Pull request by thePHTest**

### CODE REVIEW

**Comment by thePHTest** [comment]
The new commit ow safely exhausts the semaphore.

**Comment by Kelimion** [comment]
I'd love to see GraphiteMaster run this through the valgrind thread wobblificator. I recall he had a few ideas about rewriting the thread pool from scratch. His input would be most welcome.

**Comment by gingerBill** [comment]
It might be better to just completely rewrite it from scratch 🤣

**Comment by thePHTest** [comment]
I've been thinking about this more. It might be best to provide a few different thread pool implementations in core. Multiple producer + multiple consumer & single producer + multiple consumer for example.

**Pull request closed without merging**
