### PR TITLE
Only build vendor:darwin on darwin

### PR DESCRIPTION
**Pull request by flysand7**
Running

```
odin run examples/all
```

Was printing a bunch of errors (something like `msgSend` is only available on `darwin`) on my linux machine. I honestly have no idea how this wasn't caught by the CI...

### CODE REVIEW

**Comment by Kelimion** [comment]
I propose you also move these 4 from `vendor_all.odin` to its own `vendor_darwin.odin` under `examples/all`, patterned after `vendor_directx.odin`
```odin
//+build darwin
package all

import NS         "vendor:darwin/Foundation"
import MTL        "vendor:darwin/Metal"
import MTK        "vendor:darwin/MetalKit"
import CA         "vendor:darwin/QuartzCore"

_ :: NS
_ :: MTL
_ :: MTK
_ :: CA
```

**Comment by flysand7** [comment]
Should darwin vendor stuff keep it's build tags, or should I remove them?

**Comment by Kelimion** [comment]
> Should darwin vendor stuff keep it's build tags, or should I remove them?

Keep it. We also do that for `core:sys/windows` after all.

**Comment by Kelimion** [comment]
(That's why I said `also` move and not `ditch this and replace with`. ;-))

**Pull request merged**
