### PR TITLE
Add support for left/right pad

### PR DESCRIPTION
**Pull request by colrdavidson**

### CODE REVIEW

**Comment by gingerBill** [comment]
Why are you even bothering with the Builder when a simple bytes buffer is all that is required?

**Comment by colrdavidson** [comment]
Following the pattern used in left_justify/right_justify. Happy to switch things over, one sec.

**Comment by gingerBill** [comment]
Well, you can use the builder if you just reserve the precise size required.

**Comment by qgcarver** [comment]
many such cases

**Pull request closed without merging**
