### PR TITLE
Added glfw vendor support for MacOS 

### PR DESCRIPTION
**Pull request by phillvancejr**
Updated bindings.odin with the necessary foreign imports and added a freshly downloaded static glfw3 library to the vendor/glfw/lib folder

### CODE REVIEW

**Comment by gingerBill** [comment]
I'd make sure to place the macos libs in a macos specific directory

**Comment by phillvancejr** [comment]
> I'd make sure to place the macos libs in a macos specific directory

I created a darwin subdirectory in vendor/glfw/lib and moved the static library there.

**Comment by Platin21** [comment]
Why closed? Would have needed to jus5 move it over the the other folder and then committing it again.

**Comment by phillvancejr** [comment]
> Why closed? Would have needed to jus5 move it over the the other folder and then committing it again.

I'm not the most proficient git/github user so in order to make sure I had the most recent changes added today I reforked, added new changes with Bill's request and added a new pull request. How would I have made sure I had the newest changes? Could I have just done a git pull and then re commit?

**Pull request closed without merging**
