### PR TITLE
Add DLL loading procs on Windows

### PR DESCRIPTION
**Pull request by Tetralux**
- `dlopen`
- `dlclose`
- `dlsym`

### CODE REVIEW

**Comment by Tetralux** [comment]
I tried providing `dlerror` too but I was unable to figure out `FormatMessage` - if anyone knows exactly how to do that and what flags I need to pass I'll add it too.

**Comment by Tetralux** [comment]
I definitely did not accidentally base on PR off of another PR without noticing and had to remove them. *cough* Fixed now. 🤣

**Comment by gingerBill** [comment]
This is not needed as `package dynlib` is meant to do that.

**Comment by Tetralux** [comment]
Does that mean that these functions should also be removed from all platforms in favour of `package dynlib` ? @gingerBill

**Pull request closed without merging**
