### PR TITLE
Added vendor glfw support for Mac OS

### PR DESCRIPTION
**Pull request by phillvancejr**
Updated bindings and as per Ginger Bill's request added the mac specific libraries to a subdirectory in glfw/lib

### CODE REVIEW

**Comment by Kelimion** [comment]
`wasm-ld` seems not to belong, with some internal path on your system.
Neither does `core:bindgen`? I think you were a bit too enthusiastic in your most recent sync.

**Comment by phillvancejr** [comment]
> `wasm-ld` seems not to belong, with some internal path on your system. Neither does `core:bindgen`? I think you were a bit too enthusiastic in your most recent sync.

Actually I was just making some personal local changes and it slipped my mind that it would affect this pull!

**Comment by phillvancejr** [comment]
Fixed, reverted back to the previous changes. Now it should only contain the glfw and stb modifications

**Comment by esnunes** [comment]
Are the static library files compiled to Intel or Apple Silicon? Is there a way to add both?

**Comment by phillvancejr** [comment]
> Are the static library files compiled to Intel or Apple Silicon? Is there a way to add both?

Intel. I'm guessing to add Silicon someone would need to build the libs as I'm pretty sure GLFW doesn't currently distribute Silicon libs.

**Comment by Kelimion** [comment]
You could use a nested `when` of `ODIN_OS` for Darwin and another for the architecture to link to the AMD64 and AARCH64 library?

**Comment by Kelimion** [comment]
There's still the one conflict in `vendor/glfw/bindings/bindings.odin`.

**Comment by phillvancejr** [comment]
@Kelimion This is the conflict:
Master Odin has this:
```
} else {
	foreign import glfw "system:glfw"
}
```

My pull request has this:
```
} else when ODIN_OS == .Darwin {
	 foreign import glfw { 
        	"../lib/darwin/libglfw3.a",
        	"system:Cocoa.framework",
        	"system:IOKit.framework",
        	"system:OpenGL.framework",
    	}
} else {
	foreign import glfw "system:glfw"
}
```

The conflict is that my version has "glfw vendor support for Mac OS" and Odin does not, that is the whole point of the pull request. And in fact as far as I can tell this was the only conflict for a long time (from Feb 4), however this pull sat so long unchecked that master Odin changed the way ODIN_OS is checked, from strings to enums and actually created 4 new conflicts with my branch that I just updated. If there is another reason you don't want it merged then I'd prefer to just close the request without merging as I'd like to delete the 7 month old repo on my side

**Comment by Kelimion** [comment]
> If there is another reason you don't want it merged then I'd prefer to just close the request without merging as I'd like to delete the 7 month old repo on my side

It's not a matter of want, but GH won't allow it.

image

**Comment by Kelimion** [comment]
I had to add a commit resolving the issue to your master branch, @phillvancejr.

**Comment by Kelimion** [comment]
> > I had to add a commit resolving the issue to your master branch, @phillvancejr.
> 
> Thank you. Was this something that I missed doing? Or was it required on the Odin side?
It was a commit I had to make to your master branch, not on the Odin side. I don't know why, but that's what it was. In any event, the branch has now been merged.

I did notice you didn't handle Darwin's AARCH64 separately? e.g.
```odin
when ODIN_OS == .Darwin {
    when ODIN_ARCH == ... {
    
    } else when ... {
    
    }
}
```
Was that something you want to handle at some point?

**Comment by phillvancejr** [comment]
> > > I had to add a commit resolving the issue to your master branch, @phillvancejr.
> > 
> > 
> > Thank you. Was this something that I missed doing? Or was it required on the Odin side?
> 
> It was a commit I had to make to your master branch, not on the Odin side. I don't know why, but that's what it was. In any event, the branch has now been merged.
> 
> I did notice you didn't handle Darwin's AARCH64 separately? e.g.
> 
> ```odin
> when ODIN_OS == .Darwin {
>     when ODIN_ARCH == ... {
>     
>     } else when ... {
>     
>     }
> }
> ```
> 
> Was that something you want to handle at some point?

I'm still on Intel and not planning to upgrade anytime soon, but if I do and no one else has handled it, then sure I'll take care of it

**Pull request merged**
